version: "3.4"

services:
  frontend:
    build:
      context: ./
      dockerfile: ./frontend/Dockerfile
    volumes:
      - ./frontend/website-frontend:/usr/src/app
      - ./frontend/run.sh:/usr/src/app/run.sh
    ports:
      - 3000:3000






  # backend:
  #   build:
  #     context: ./
  #     dockerfile: docker/Dockerfile
  #   env_file:
  #     - .env
  #   ports:
  #     - 8080:8080